-- 기관 종류 및 주소 필드 추가
ALTER TABLE orgs ADD COLUMN org_type VARCHAR(32) DEFAULT NULL;
ALTER TABLE orgs ADD COLUMN address_region VARCHAR(64) DEFAULT NULL;
ALTER TABLE orgs ADD COLUMN address_detail VARCHAR(300) DEFAULT NULL;
