DELETE FROM chat_emoticons WHERE id LIKE 'emo_%';
DELETE FROM files WHERE id LIKE 'file_emo_%';
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_001', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_001/download', 'image/png', 781886, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_001', '잠자기', 'file_emo_001', 1, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_002', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_002/download', 'image/png', 584311, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_002', '냠냠', 'file_emo_002', 2, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_003', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_003/download', 'image/png', 483977, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_003', '인사', 'file_emo_003', 3, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_004', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_004/download', 'image/png', 649231, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_004', '출발', 'file_emo_004', 4, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_005', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_005/download', 'image/png', 700070, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_005', '열공', 'file_emo_005', 5, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_006', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_006/download', 'image/png', 685913, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_006', '하하하', 'file_emo_006', 6, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_007', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_007/download', 'image/png', 709842, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_007', '엉엉', 'file_emo_007', 7, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_008', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_008/download', 'image/png', 638459, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_008', '화남', 'file_emo_008', 8, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_009', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_009/download', 'image/png', 783474, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_009', '굿모닝이야옹', 'file_emo_009', 9, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_010', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_010/download', 'image/png', 644373, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_010', '안녕하세요', 'file_emo_010', 10, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_011', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_011/download', 'image/png', 771583, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_011', '감사합니다', 'file_emo_011', 11, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_012', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_012/download', 'image/png', 630858, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_012', '졸려요', 'file_emo_012', 12, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_013', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_013/download', 'image/png', 818124, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_013', '재밌다', 'file_emo_013', 13, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_014', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_014/download', 'image/png', 754111, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_014', '기적이야', 'file_emo_014', 14, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_015', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_015/download', 'image/png', 704370, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_015', '공부중', 'file_emo_015', 15, 'active', 'u_ai_podo', NOW());
INSERT INTO files (id, owner_id, purpose, url, mime, size, status, created_at, updated_at) VALUES ('file_emo_016', 'u_ai_podo', 'chat-emoticon', '/v1/files/file_emo_016/download', 'image/png', 846917, 'uploaded', NOW(), NOW());
INSERT INTO chat_emoticons (id, name, file_id, sort_order, status, created_by, created_at) VALUES ('emo_016', '일하는중', 'file_emo_016', 16, 'active', 'u_ai_podo', NOW());
